//! The flag rows of `scp` and `sftp`: a row for each letter of the usage of
//! OpenSSH 10.3p1 (T-139), supported, accepted, or refused by name, so no
//! letter of those command lines is an unknown flag. `-s`, `-R` and `-B` are
//! switches on `scp` and take a value on `sftp`, so each verb has its own
//! table. Neither has `--timeout`: OpenSSH's have none, and each wait of a
//! copy has its own limit.

use super::{row, FlagKind, FlagRow};

/// **`scp`.** `-346ABCOpqRrsTv`, and the values `-c -D -F -i -J -l -o -P -S -X`.
pub const SCP_FLAGS: &[FlagRow] = &[
    row(Some('3'), "through-this-host", None, FlagKind::Accepted,
        "a copy between two hosts goes through this host; podssh always does so", None),
    row(Some('4'), "ipv4-only", None, FlagKind::Supported, "use IPv4 addresses only", None),
    row(Some('6'), "ipv6-only", None, FlagKind::Supported, "use IPv6 addresses only", None),
    row(Some('A'), "forward-agent", None, FlagKind::Refused,
        "agent forwarding is not supported", Some("no flag")),
    row(Some('B'), "batch-mode", None, FlagKind::Supported,
        "batch mode: never ask for a password or a passphrase (BatchMode=yes)", None),
    row(Some('C'), "compress", None, FlagKind::Supported, "compress the connection", None),
    row(Some('O'), "legacy-scp", None, FlagKind::Refused,
        "the legacy SCP protocol: podssh copies over SFTP, or by exec", Some("no flag")),
    row(Some('p'), "preserve", None, FlagKind::Refused,
        "keeping the mode and the times of a file is not implemented yet", Some("no flag")),
    row(Some('q'), "quiet", None, FlagKind::Supported,
        "quiet: no messages from podssh itself, errors included", None),
    row(Some('R'), "remote-copy", None, FlagKind::Refused,
        "a copy that the first host makes with its own scp", Some("no flag: the copy goes through this host")),
    row(Some('r'), "recursive", None, FlagKind::Refused,
        "copying a directory is not implemented yet", Some("one command for each file")),
    row(Some('s'), "sftp-protocol", None, FlagKind::Accepted, "the SFTP protocol; podssh uses it already", None),
    row(Some('T'), "no-name-check", None, FlagKind::Accepted,
        "no check of the names that a server sends; podssh names each file itself", None),
    row(Some('v'), "verbose", None, FlagKind::Supported, "raise log level; repeatable", None),
    row(Some('c'), "cipher", Some("CIPHERS"), FlagKind::Refused,
        "podssh negotiates its own modern ciphers", Some("no flag")),
    row(Some('D'), "sftp-server-path", Some("PATH"), FlagKind::Refused,
        "a local SFTP server program in place of a host", Some("no flag")),
    row(Some('F'), "config", Some("CONFIG"), FlagKind::Supported,
        "read this ssh_config file in place of ~/.ssh/config; none reads no file", None),
    row(Some('i'), "identity-file", Some("FILE"), FlagKind::Supported,
        "identity file, repeatable; also -oIdentityFile=", None),
    row(Some('J'), "jump-host", Some("HOSTS"), FlagKind::Supported,
        "log in through these hosts first: [user@]host[:port][,...]", None),
    row(Some('l'), "limit", Some("KBITS"), FlagKind::Refused,
        "a limit of the bandwidth is not implemented yet", Some("no flag")),
    row(Some('o'), "option", Some("NAME=VALUE"), FlagKind::Supported,
        "an OpenSSH option, as -o Name=Value; repeatable", None),
    row(Some('P'), "port", Some("PORT"), FlagKind::Supported, "port to connect to; this is scp's -P", None),
    row(Some('S'), "program", Some("PROGRAM"), FlagKind::Refused,
        "another program for the connection: podssh is the connection", Some("no flag")),
    row(Some('X'), "sftp-option", Some("OPTION"), FlagKind::Refused,
        "SFTP's buffer and its requests in flight are not set yet", Some("no flag")),
    row(None, "jsonl", None, FlagKind::Supported, "one JSON object per event on stdout", None),
    row(None, "relay-host", Some("HOSTS"), FlagKind::Supported,
        "relay hosts to try in order, HOST[:PORT][,...] (default: env PODSSH_RELAY, else the built-in relay and its pool)", None),
    row(None, "relay-addr", Some("HOST=IP"), FlagKind::Supported,
        "use IP for HOST instead of DNS, HOST=IP[,...]; also env PODSSH_RELAY_ADDR (for hosts with no DNS)", None),
    row(None, "ca-file", Some("FILE"), FlagKind::Supported,
        "trust only the CA certificates in FILE for the relay (default: env SSL_CERT_FILE, else system and built-in roots)", None),
    row(None, "direct", None, FlagKind::Supported,
        "connect without the relay: TCP, through HTTPS_PROXY when one is set", None),
];

/// **`sftp`.** `-46AaCfNpqrv`, and the values
/// `-B -b -c -D -F -i -J -l -o -P -R -S -s -X`.
pub const SFTP_FLAGS: &[FlagRow] = &[
    row(Some('4'), "ipv4-only", None, FlagKind::Supported, "use IPv4 addresses only", None),
    row(Some('6'), "ipv6-only", None, FlagKind::Supported, "use IPv6 addresses only", None),
    row(Some('A'), "forward-agent", None, FlagKind::Refused,
        "agent forwarding is not supported", Some("no flag")),
    row(Some('a'), "append", None, FlagKind::Accepted,
        "go on with an interrupted transfer; podssh does so by itself, from its side file", None),
    row(Some('C'), "compress", None, FlagKind::Supported, "compress the connection", None),
    row(Some('f'), "fsync", None, FlagKind::Accepted,
        "flush each file to the server's disk; podssh always does, where the server can", None),
    row(Some('N'), "not-quiet", None, FlagKind::Accepted,
        "not quiet in batch mode; podssh's batch mode is not quiet", None),
    row(Some('p'), "preserve", None, FlagKind::Refused,
        "keeping the mode and the times of a file is not implemented yet", Some("no flag")),
    row(Some('q'), "quiet", None, FlagKind::Supported,
        "quiet: no messages from podssh itself, errors included", None),
    row(Some('r'), "recursive", None, FlagKind::Refused,
        "copying a directory is not implemented yet", Some("one command for each file")),
    row(Some('v'), "verbose", None, FlagKind::Supported, "raise log level; repeatable", None),
    row(Some('B'), "buffer-size", Some("BYTES"), FlagKind::Refused,
        "SFTP's buffer size is not set yet", Some("no flag")),
    row(Some('b'), "batch-file", Some("FILE"), FlagKind::Supported,
        "read the commands from FILE, - for stdin; a failed command ends the batch unless it starts with -", None),
    row(Some('c'), "cipher", Some("CIPHERS"), FlagKind::Refused,
        "podssh negotiates its own modern ciphers", Some("no flag")),
    row(Some('D'), "sftp-server-path", Some("PATH"), FlagKind::Refused,
        "a local SFTP server program in place of a host", Some("no flag")),
    row(Some('F'), "config", Some("CONFIG"), FlagKind::Supported,
        "read this ssh_config file in place of ~/.ssh/config; none reads no file", None),
    row(Some('i'), "identity-file", Some("FILE"), FlagKind::Supported,
        "identity file, repeatable; also -oIdentityFile=", None),
    row(Some('J'), "jump-host", Some("HOSTS"), FlagKind::Supported,
        "log in through these hosts first: [user@]host[:port][,...]", None),
    row(Some('l'), "limit", Some("KBITS"), FlagKind::Refused,
        "a limit of the bandwidth is not implemented yet", Some("no flag")),
    row(Some('o'), "option", Some("NAME=VALUE"), FlagKind::Supported,
        "an OpenSSH option, as -o Name=Value; repeatable", None),
    row(Some('P'), "port", Some("PORT"), FlagKind::Supported, "port to connect to; this is sftp's -P", None),
    row(Some('R'), "requests", Some("COUNT"), FlagKind::Refused,
        "SFTP's requests in flight are not set yet", Some("no flag")),
    row(Some('S'), "program", Some("PROGRAM"), FlagKind::Refused,
        "another program for the connection: podssh is the connection", Some("no flag")),
    row(Some('s'), "subsystem-name", Some("NAME"), FlagKind::Supported,
        "the subsystem of the SFTP server (default: sftp)", None),
    row(Some('X'), "sftp-option", Some("OPTION"), FlagKind::Refused,
        "SFTP's buffer and its requests in flight are not set yet", Some("no flag")),
    row(None, "relay-host", Some("HOSTS"), FlagKind::Supported,
        "relay hosts to try in order, HOST[:PORT][,...] (default: env PODSSH_RELAY, else the built-in relay and its pool)", None),
    row(None, "relay-addr", Some("HOST=IP"), FlagKind::Supported,
        "use IP for HOST instead of DNS, HOST=IP[,...]; also env PODSSH_RELAY_ADDR (for hosts with no DNS)", None),
    row(None, "ca-file", Some("FILE"), FlagKind::Supported,
        "trust only the CA certificates in FILE for the relay (default: env SSL_CERT_FILE, else system and built-in roots)", None),
    row(None, "direct", None, FlagKind::Supported,
        "connect without the relay: TCP, through HTTPS_PROXY when one is set", None),
];
