//! The flag table, and it is the *only* place a flag is written down.
//!
//! ⛔ `docs/spec/06-cli.md`:154-161 makes the manual page autogenerated, current
//! and drift-free as three separate obligations, and the third — drift-free —
//! is the one that fails silently. The way all three hold is that there is
//! exactly one list here and two renderers walk it:
//!
//! * `--help` renders it, via [`crate::help`].
//! * `podssh man` renders it, via [`crate::man`], as text and as roff.
//!
//! ⛔ A flag defined here and unimplemented is a refusal naming itself. It is
//! never a stub that exits 0 (`06-cli.md`:244-245), and `refused_because` is
//! where the refusal text comes from.
//!
//! The rows are checked by `tests/flag_table.rs` (the `ssh` short flags are a
//! reviewed list there) and by the help and man page parity tests. The
//! specification they were once matched against is archived.

/// What a flag does, in enough words for a man page and short enough for help.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum FlagKind {
    /// A flag that is fully wired. It parses and it is handed to the session.
    Supported,
    /// A flag that parses and is deliberately ignored, and says so.
    Accepted,
    /// A real OpenSSH flag podssh does not implement in this release. It parses,
    /// and using it is a refusal naming what to use instead.
    Refused,
    /// A flag that exists in OpenSSH's vocabulary and podssh will not carry.
    /// It never parses; mentioning it names `-W`.
    NotInFirstRelease,
}

/// One row of the table. `Option<&str>` for `short` because some flags are long
/// only (`--StrictHostKeyChecking`, and every E33/E35 flag added later).
#[derive(Clone, Copy, Debug)]
pub struct FlagRow {
    pub short: Option<char>,
    pub long: &'static str,
    /// The metavariable after the flag in a man page: `PORT`, `FILE`, `TAG`.
    pub arg: Option<&'static str>,
    pub kind: FlagKind,
    /// The help text. One line, no trailing period — `ssh` writes them without.
    pub help: &'static str,
    /// For a `Refused` row, what the user should type instead.
    pub instead: Option<&'static str>,
}

impl FlagRow {
    /// The flag as a user types it, for messages and for the man emitter.
    pub fn spelling(&self) -> String {
        match self.short {
            Some(c) => format!("-{c}"),
            None => format!("--{}", self.long),
        }
    }

    /// The spelling with its metavariable, as it appears in `Usage:`.
    pub fn usage_form(&self) -> String {
        match self.arg {
            Some(a) => format!("{} {a}", self.spelling()),
            None => self.spelling(),
        }
    }
}

const fn row(
    short: Option<char>,
    long: &'static str,
    arg: Option<&'static str>,
    kind: FlagKind,
    help: &'static str,
    instead: Option<&'static str>,
) -> FlagRow {
    FlagRow { short, long, arg, kind, help, instead }
}

/// ⛔ **The one-line description of the whole program**, and it is here rather
/// than in a renderer because two renderers write it: `--help`'s banner and
/// the page's `.SH NAME` (E32). ⛔ A sentence copied into both is a sentence
/// that drifts, and this one names the program's whole premise.
pub const ABOUT: &str = "no-privilege SSH over a WebSocket relay";

/// ⛔ **The universal option, written down once.** Every verb accepts
/// `--help`; it is not a row in any verb's table because the *parser* declares
/// it ([`crate::tree::verb_command`]) rather than parsing it from a table.
/// ⛔ E32's page renders it for every section, and `--help` renders it for
/// every verb, ⛔ so the sentence lives here and the parity gate compares the
/// two renderings of it rather than trusting either copy.
pub const HELP_FLAG: FlagRow = row(
    None,
    "help",
    None,
    FlagKind::Supported,
    "Print help for this subcommand and exit",
    None,
);

/// ⛔ **`ssh`'s flags, and the whole of `06-cli.md`:58-72's table.**
///
/// ⛔ **The `-P` row is `Accepted`, not `Refused`, and it is `TAG`.** The
/// entry's premise said `-P` is not an OpenSSH flag and must be refused; the
/// specification has since been corrected (see `docs/TODO/cli/surface.md`), and
/// the correction is right. MEASURED 2026-10-02, this machine, Git Bash on
/// Windows, OpenSSH_10.3p1:
///   `ssh -G -P mytag example.org` → `tag mytag`; without `-P` there is no
///   `tag` line at all. `ssh -G -P2222 example.org` → `port 22`, `tag 2222`.
/// ⛔ **Refusing it would refuse a flag a user has memorised and that OpenSSH
/// honours**, which breaks the parity promise the whole entry exists for.
/// `-P` remains `scp`'s port — see [`SCP_FLAGS`], which is why the refusal
/// below is per-verb and never global.
pub const SSH_FLAGS: &[FlagRow] = &[
    row(Some('p'), "port", Some("PORT"), FlagKind::Supported,
        "port to connect to; never a proxy port", None),
    row(Some('l'), "login-name", Some("USER"), FlagKind::Supported,
        "user to log in as; also user@host", None),
    row(Some('i'), "identity-file", Some("FILE"), FlagKind::Supported,
        "identity file, repeatable; also -oIdentityFile=", None),
    row(Some('J'), "jump-host", Some("HOSTS"), FlagKind::Supported,
        "log in through these hosts first: [user@]host[:port][,...]", None),
    row(Some('N'), "no-remote-command", None, FlagKind::Supported,
        "run nothing; stay connected until the server closes", None),
    row(Some('n'), "stdin-null", None, FlagKind::Supported,
        "do not read stdin; the remote side sees end of input at once", None),
    row(Some('s'), "subsystem", None, FlagKind::Supported,
        "the command is a subsystem name, such as sftp", None),
    row(Some('t'), "force-tty", None, FlagKind::Supported,
        "request a pty; twice to request one even without a local tty", None),
    row(Some('T'), "disable-tty", None, FlagKind::Supported,
        "disable tty allocation", None),
    row(Some('e'), "escape-char", Some("CHAR"), FlagKind::Supported,
        "escape character for sessions with a pty, or none (default ~)", None),
    row(Some('C'), "compress", None, FlagKind::Supported,
        "ask the server for compression", None),
    row(Some('4'), "ipv4-only", None, FlagKind::Supported,
        "use IPv4 only; forwarded to the relay's ?family=4", None),
    row(Some('6'), "ipv6-only", None, FlagKind::Supported,
        "use IPv6 only; forwarded to the relay's ?family=6", None),
    row(Some('W'), "stdio-forward", Some("HOST:PORT"), FlagKind::Supported,
        "stdin and stdout become a connection the server opens to HOST:PORT", None),
    row(Some('E'), "log-file", Some("LOGFILE"), FlagKind::Supported,
        "append podssh's own messages to a file instead of stderr", None),
    row(Some('F'), "config", Some("CONFIG"), FlagKind::Supported,
        "an ssh_config file; only none is accepted yet (use -o)", None),
    row(Some('v'), "verbose", None, FlagKind::Supported,
        "raise log level; repeatable", None),
    row(Some('q'), "quiet", None, FlagKind::Supported,
        "quiet: no messages from podssh itself, errors included", None),
    row(Some('V'), "version", None, FlagKind::Supported,
        "print the version and exit", None),
    // ⛔ `-o` is here because `06-cli.md`:61 and :65 both spell OpenSSH's
    // option syntax as `-oIdentityFile=` and `-o LogLevel=`, so a user typing
    // the flag they have memorised must find it. ⛔ **This row was MISSING from
    // the first version of this table and the flag-table check caught it**,
    // failing with *"06-cli.md:58-72 names ["-o", "-o"], which the tree does
    // not have"* — ⛔ and the gate is load-bearing rather than incidental,
    // because a documented flag that does not parse is a promise the binary
    // breaks in the direction a user notices.
    row(Some('o'), "option", Some("NAME=VALUE"), FlagKind::Supported,
        "an OpenSSH option, as -o Name=Value; repeatable", None),
    row(None, "StrictHostKeyChecking", Some("yes|accept-new|no|ask"), FlagKind::Supported,
        "host key policy, as -o StrictHostKeyChecking; there is no --insecure", None),
    row(None, "UserKnownHostsFile", Some("FILE"), FlagKind::Supported,
        "known-hosts file to consult, as -o UserKnownHostsFile", None),
    row(None, "LogLevel", Some("LEVEL"), FlagKind::Supported,
        "quiet, fatal, error, info, verbose, debug", None),
    row(None, "ConnectTimeout", Some("SECONDS"), FlagKind::Supported,
        "bound on the SSH handshake, as -o ConnectTimeout", None),
    row(None, "relay-host", Some("HOSTS"), FlagKind::Supported,
        "relay hosts to try in order, HOST[:PORT][,...] (default: env PODSSH_RELAY, else the built-in relay and its pool)", None),
    row(None, "relay-addr", Some("HOST=IP"), FlagKind::Supported,
        "use IP for HOST instead of DNS, HOST=IP[,...]; also env PODSSH_RELAY_ADDR (for hosts with no DNS)", None),
    row(None, "ca-file", Some("FILE"), FlagKind::Supported,
        "trust only the CA certificates in FILE for the relay (default: env SSL_CERT_FILE, else system and built-in roots)", None),
    row(None, "direct", None, FlagKind::Supported,
        "connect without the relay: TCP, through HTTPS_PROXY when one is set", None),
    // These two disable things podssh never does, so they need no work.
    row(Some('x'), "no-x11", None, FlagKind::Supported,
        "no X11 forwarding (podssh never forwards X11)", None),
    row(Some('a'), "no-agent-forwarding", None, FlagKind::Supported,
        "no agent forwarding (podssh never forwards the agent)", None),
    // ⛔ Accepted and ignored. `ssh -G` proves it is a Tag and not a port, and
    // a user who has memorised `-P` must not be taught a second way to spell it.
    row(Some('P'), "tag", Some("TAG"), FlagKind::Accepted,
        "Tag, as OpenSSH ssh reads it", None),
    // ⛔ Refused rows. Each names what to type instead; none prints a usage block.
    row(Some('L'), "forward-local", Some("SPEC"), FlagKind::Refused,
        "podssh never binds a listener, so -L is refused", Some("-W HOST:PORT")),
    row(Some('R'), "forward-remote", Some("SPEC"), FlagKind::Refused,
        "remote forwarding is not in the first release", Some("-W HOST:PORT")),
    row(Some('D'), "dynamic-forward", Some("SPEC"), FlagKind::Refused,
        "podssh never binds a listener, so -D is refused", Some("-W HOST:PORT")),
    row(Some('A'), "forward-agent", None, FlagKind::Refused,
        "agent forwarding is not supported", Some("-J HOST (log in through the jump host)")),
    row(Some('B'), "bind-interface", Some("IFACE"), FlagKind::Refused,
        "podssh never binds; the relay chooses the source address", Some("no flag")),
    row(Some('b'), "bind-address", Some("ADDR"), FlagKind::Refused,
        "podssh never binds; the relay chooses the source address", Some("no flag")),
];

/// ⛔ **`cp` / `mv` and their `scp` / `sftp` aliases (E36).** The flags are
/// defined here so they parse and are refused correctly; E36 owns the
/// behaviour.
pub const CP_FLAGS: &[FlagRow] = &[
    // ⛔ **The `-P` fork, and it is measured rather than remembered.**
    // MEASURED 2026-10-02, this machine, OpenSSH_10.3p1:
    //   `scp` usage prints `[-P port]`, `sftp -h` prints `[-P port]`, and
    //   `ssh` usage prints `[-P tag]`. Three programs, one letter, two meanings.
    row(Some('P'), "port", Some("PORT"), FlagKind::Supported,
        "port to connect to; this is scp's -P", None),
    row(Some('p'), "preserve", None, FlagKind::Supported,
        "preserve mode and mtime where the filesystem allows", None),
    row(Some('i'), "identity-file", Some("FILE"), FlagKind::Supported,
        "identity file", None),
    row(Some('r'), "recursive", None, FlagKind::Supported,
        "copy directories", None),
    row(Some('F'), "config", Some("CONFIG"), FlagKind::Supported,
        "an OpenSSH-format config, read for its shared keys", None),
    row(None, "jsonl", None, FlagKind::Supported,
        "one JSON object per event on stdout", None),
    row(None, "timeout", Some("DURATION"), FlagKind::Supported,
        "bound the transfer; required with no TTY", None),
];

/// ⛔ **`chat` and its `irc` alias (E33).** `--jsonl` and `--timeout` are E33's
/// and appear in the tree because a flag that does not parse cannot be refused.
pub const CHAT_FLAGS: &[FlagRow] = &[
    row(None, "send", Some("MESSAGE"), FlagKind::Supported,
        "send one message and exit; never prompts", None),
    row(None, "sendfile", Some("FILE"), FlagKind::Supported,
        "send each line of a file as a message", None),
    row(None, "jsonl", None, FlagKind::Supported,
        "one JSON object per event on stdout", None),
    row(None, "timeout", Some("DURATION"), FlagKind::Supported,
        "bound the run; required when stdin is not a TTY", None),
    row(None, "nick", Some("NICK"), FlagKind::Supported,
        "nickname to use", None),
];

/// ⛔ **`ts` and its `tailscale` alias (E39, increment 4a scaffold).** r2
/// spelling: `ts`-prefixed flags; `-W` is the byte-pipe target with ssh's own
/// `stdio-forward` row shape. 4a parses all three forms and refuses naming
/// E39 — behaviour (`-W` pipe, chain) is 4b.
pub const TS_FLAGS: &[FlagRow] = &[
    row(None, "ts-mode", Some("MODE"), FlagKind::Supported,
        "auto tun socks tcp relay: force one tailnet route, no fallback", None),
    row(None, "ts-proxy", Some("URL"), FlagKind::Supported,
        "CONNECT proxy for every outbound TCP path", None),
    row(None, "ts-auth-key-file", Some("FILE"), FlagKind::Supported,
        "tailnet auth key file; never passed on argv", None),
    row(None, "ts-state", Some("FILE"), FlagKind::Supported,
        "node key-state file, created when missing", None),
    row(None, "ts-ephemeral", None, FlagKind::Supported,
        "register an ephemeral node", None),
    row(None, "ts-relay", Some("HOST"), FlagKind::Supported,
        "DERP-over-WebSocket relay for relay mode", None),
    row(None, "ts-wait-allowlist", Some("DURATION"), FlagKind::Supported,
        "wait this long for relay admission; default fail-fast", None),
    row(Some('W'), "stdio-forward", Some("HOST:PORT"), FlagKind::Supported,
        "byte pipe over the tailnet: stdio becomes the stream", None),
    row(None, "jsonl", None, FlagKind::Supported,
        "one JSON object per event on stdout", None),
    row(None, "timeout", Some("DURATION"), FlagKind::Supported,
        "bound the run; required when stdin is not a TTY", None),
];

/// `man`: the manual of this binary, generated from these tables.
pub const MAN_FLAGS: &[FlagRow] = &[
    row(None, "no-pager", None, FlagKind::Supported,
        "write the whole manual to stdout; never page, even on a terminal", None),
    row(None, "roff", None, FlagKind::Supported,
        "write the manual as a man(7) page instead of text, for man -l; never paged", None),
];

/// ⛔ **`relay` (E35).**
pub const RELAY_FLAGS: &[FlagRow] = &[
    row(None, "jsonl", None, FlagKind::Supported,
        "one JSON object per event on stdout", None),
    row(None, "relay-host", Some("URL"), FlagKind::Supported,
        "relay base URL, overriding the compiled default", None),
    row(None, "timeout", Some("DURATION"), FlagKind::Supported,
        "bound the request", None),
];

/// ⛔ **`proxy`, E08.** ⛔ `06-cli.md`:19 says it is **not an alias** of `ssh`
/// and behaves differently, so it gets its own flag list rather than sharing
/// `ssh`'s. Sharing them is exactly how the nested-SSH mistake the line names
/// gets invited.
pub const PROXY_FLAGS: &[FlagRow] = &[
    row(None, "stdin-stdout", None, FlagKind::Supported,
        "a byte pipe on stdin/stdout; not an SSH client", None),
    row(None, "relay-host", Some("HOSTS"), FlagKind::Supported,
        "relay hosts to try in order, HOST[:PORT][,...] (default: env PODSSH_RELAY, else the built-in relay and its pool)", None),
    row(None, "relay-addr", Some("HOST=IP"), FlagKind::Supported,
        "use IP for HOST instead of DNS, HOST=IP[,...]; also env PODSSH_RELAY_ADDR (for hosts with no DNS)", None),
    row(None, "ca-file", Some("FILE"), FlagKind::Supported,
        "trust only the CA certificates in FILE (default: env SSL_CERT_FILE, else system and built-in roots)", None),
];

/// `doctor` checks the relay path `ssh` and `proxy` would take, so it takes
/// their relay settings.
pub const DOCTOR_FLAGS: &[FlagRow] = &[
    row(None, "relay-host", Some("HOSTS"), FlagKind::Supported,
        "relay hosts to check, HOST[:PORT][,...] (default: env PODSSH_RELAY, else the built-in relay and its pool)", None),
    row(None, "relay-addr", Some("HOST=IP"), FlagKind::Supported,
        "use IP for HOST instead of DNS, HOST=IP[,...]; also env PODSSH_RELAY_ADDR (for hosts with no DNS)", None),
    row(None, "ca-file", Some("FILE"), FlagKind::Supported,
        "trust only the CA certificates in FILE (default: env SSL_CERT_FILE, else system and built-in roots)", None),
];

/// `keygen` takes the `ssh-keygen` flags scripts use. `-N` exists so that
/// `-N ''` works; a non-empty passphrase there is refused, because every
/// process on the host can read a command line.
pub const KEYGEN_FLAGS: &[FlagRow] = &[
    row(Some('t'), "type", Some("TYPE"), FlagKind::Supported,
        "key type: ed25519 (the default), ecdsa or rsa", None),
    row(Some('b'), "bits", Some("BITS"), FlagKind::Supported,
        "key size: ecdsa 256 (the default), 384 or 521; rsa 2048 to 16384 (default 3072)", None),
    row(Some('f'), "file", Some("FILE"), FlagKind::Supported,
        "the private key's file; the public key goes to FILE.pub (default ~/.ssh/id_TYPE)", None),
    row(Some('N'), "new-passphrase", Some("PHRASE"), FlagKind::Supported,
        "-N '' for a key with no passphrase; without -N, podssh asks (terminal or SSH_ASKPASS)", None),
    row(Some('C'), "comment", Some("COMMENT"), FlagKind::Supported,
        "the key's comment (default USER@HOST)", None),
    row(Some('q'), "quiet", None, FlagKind::Supported,
        "print nothing but errors", None),
    row(Some('y'), "print-public", None, FlagKind::Supported,
        "print the public key of the private key in -f FILE", None),
    row(Some('l'), "fingerprint", None, FlagKind::Supported,
        "print the fingerprint of the key in -f FILE", None),
];

/// One verb: its names, its flags, and the flag table its `-P` belongs to.
#[derive(Clone, Copy)]
pub struct Verb {
    /// The canonical name, and the one `--help` prints.
    pub name: &'static str,
    /// Every spelling that resolves to this verb. `06-cli.md`:21-22 makes
    /// `chat`/`irc` and `cp`/`scp`/`sftp` pairs, and `02-architecture.md`:229,
    /// 234 and 241 name `connect`/`node`/`operator`.
    pub aliases: &'static [&'static str],
    pub flags: &'static [FlagRow],
    pub about: &'static str,
}

/// ⛔ **Every verb, in the order `--help` prints them.** `aliases` is how the
/// no-subcommand handler finds a verb, and it is the same list the distance
/// stage searches — ⛔ one list, so a verb the handler cannot suggest is a verb
/// that is not there.
pub const VERBS: &[Verb] = &[
    Verb { name: "ssh", aliases: &["ssh", "connect"], flags: SSH_FLAGS,
        about: "the OpenSSH-compatible client, over the relay" },
    Verb { name: "proxy", aliases: &["proxy"], flags: PROXY_FLAGS,
        about: "ProxyCommand form: a byte pipe, not an SSH client" },
    Verb { name: "node", aliases: &["node"], flags: &[],
        about: "reverse mode: expose a local service to operators" },
    Verb { name: "operator", aliases: &["operator"], flags: &[],
        about: "reverse mode, operator side: raw bytes to a named node" },
    Verb { name: "chat", aliases: &["chat", "irc"], flags: CHAT_FLAGS,
        about: "the IRC client" },
    Verb { name: "cp", aliases: &["cp", "scp", "sftp"], flags: CP_FLAGS,
        about: "copy files to or from a remote host" },
    Verb { name: "mv", aliases: &["mv"], flags: CP_FLAGS,
        about: "move files; across hosts this is a copy and a delete" },
    Verb { name: "man", aliases: &["man"], flags: MAN_FLAGS,
        about: "this manual: each command, flag, variable, file and exit code" },
    Verb { name: "relay", aliases: &["relay"], flags: RELAY_FLAGS,
        about: "relay status, facts, and pair management" },
    Verb { name: "status", aliases: &["status"], flags: &[],
        about: "one-shot state, one line, machine-readable" },
    Verb { name: "doctor", aliases: &["doctor"], flags: DOCTOR_FLAGS,
        about: "what this host allows and whether the relay works: ok, FAIL or ???? per check" },
    Verb { name: "keygen", aliases: &["keygen", "ssh-keygen"], flags: KEYGEN_FLAGS,
        about: "make an SSH key pair, or print a key's public key or fingerprint" },
    Verb { name: "ts", aliases: &["ts", "tailscale"], flags: TS_FLAGS,
        about: "the tailnet node and byte pipe, over DERP" },
];

/// Every verb that dispatch refuses as "not implemented yet", with the roadmap
/// milestone (docs/ROADMAP.md) that builds it. The milestone is for
/// maintainers; users only see that the verb is not implemented.
///
/// A verb with its own dispatch arm (`ssh`, `proxy`, `doctor`, `keygen`,
/// `man`, `ts`) is handled before this table is consulted. When a verb gets
/// its own arm, remove its row here and add it to `DISPATCHED` in
/// `tests/flag_table.rs`; dispatch treats a verb with neither an arm nor a row
/// as an internal error, never as success.
pub const VERB_OWNER: &[(&str, &str)] = &[
    ("node", "M4"),
    ("operator", "M4"),
    ("chat", "M8"),
    ("cp", "M5"),
    ("mv", "M5"),
    ("relay", "M4"),
    ("status", "M8"),
];

/// Whether a verb does something in this binary. `--help` and the manual
/// both show it, so neither can offer a command that only refuses.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Availability {
    Works,
    /// Parses, and refuses with exit 70 (a row of [`VERB_OWNER`]).
    NotYet,
    /// Needs a cargo feature this binary was built without (`ts`).
    NotInBuild,
}

pub fn availability(verb: &Verb) -> Availability {
    if verb.name == "ts" && !cfg!(feature = "ts") {
        Availability::NotInBuild
    } else if VERB_OWNER.iter().any(|(name, _)| *name == verb.name) {
        Availability::NotYet
    } else {
        Availability::Works
    }
}

/// The options read before any verb (`tree::parse`), for `--help` and the
/// manual.
pub const TOP_OPTIONS: &[(&str, &str, &str)] = &[
    ("-h", "--help", "Print help"),
    ("-V", "--version", "Print version"),
];

/// Find a verb by any of its spellings. Returns `None` for anything else —
/// ⛔ and `None` is what makes `podssh example.org` a refusal rather than a
/// connection attempt.
pub fn verb_for(token: &str) -> Option<&'static Verb> {
    VERBS.iter().find(|v| v.aliases.contains(&token))
}

/// The canonical name for a spelling the user typed, if it is one podssh knows.
pub fn canonical_name(token: &str) -> Option<&'static str> {
    verb_for(token).map(|v| v.name)
}