//! `podssh man` — the roff page, rendered from the same tree `--help` renders.
//!
//! ⛔ **One tree, walked twice.** `docs/spec/06-cli.md`:154-161 makes the page
//! *"autogenerated"*, *"current"* and *"drift-free"* three separate
//! obligations and gives one mechanism for all three: **one definition, two
//! renderers**. ⛔ Nothing here writes a flag down: every verb, alias, flag,
//! metavariable and description comes from [`crate::flags::VERBS`], and ⛔
//! `crate::flags::HELP_FLAG` and `crate::flags::ABOUT` are shared with
//! `--help` so that even the two sentences have one copy.
//!
//! ⛔ **No checked-in template and no `include_str!` of a hand-written page.**
//! `docs/TODO/cli/man.md`:165-173 chooses runtime generation over a committed
//! `.1` file, and the reason is that a template is a *second source of truth*:
//! ⛔ a page that says *"`-L` is refused"* stays syntactically current while
//! the refusal is deleted from the table, ⛔ and the set-equality gate cannot
//! tell a stale sentence from a fresh one. ⛔ There is no file to read here at
//! all — [`page`] returns a `String` built from the table.
//!
//! ⛔ **`.It` and `.Fl` are the two macros the flag list uses**, named by
//! `06-cli.md`:163-165 as what the gate extracts (*"every `.It`/`.Fl` from the
//! man page"*). ⛔ They are mdoc's, not man(7)'s, so ⛔ **the page defines them
//! itself** in [`DEFINITIONS`]: `.It` is `.TP` and `.Fl` prints its arguments
//! in bold. ⛔ A page that invokes a request it never defines is a page no
//! renderer can render — ⛔ and `.de` is a plain roff request, so the output is
//! one dialect of roff rather than two documents stapled together.
//!
//! ⛔ **An emitter, not a parser.** `man.md`:138-140: *"podssh emits; it does
//! not interpret troff"*, and the subset is *"bounded by what its own output
//! contains"* — which [`MACROS`] is, as a constant that this module's own
//! `the_page_uses_only_the_macros_it_defines` test checks the emitted page
//! against. ⛔ `tests/man_page.rs` checks the *other* obligations, the
//! no-process/no-token/no-URL ones.
//!
//! ⛔ **What the page must never carry** (`man.md`:155-160): the relay host
//! (E06's drift gate owns it), any token or credential, and any sentence
//! copied out of `docs/spec/`. `tests/man_page.rs` asserts the first two.

use crate::flags::{FlagRow, Verb, VERBS};
use std::fmt::Write as _;
use std::io::{BufRead, Write};

/// ⛔ **Every request the emitted page is allowed to contain.** ⛔ A whitelist
/// and not a rule, because the assertion it feeds is *"no line of this page
/// starts a macro the emitter did not intend"* — which is `man.md`:233's
/// plant 7, the troff-injection defect.
pub const MACROS: &[&str] = &[
    ".TH", ".SH", ".SS", ".It", ".Fl", ".B", ".I", ".BR", ".IR", ".RI", ".br", ".TP", ".de", "..",
];

/// ⛔ **The headings the emitter writes, and nothing else may appear.**
/// ⛔ Checked rather than assumed: a `.SH` line that came out of a table string
/// would be an injected section, ⛔ and a heading is where a reader looks first.
/// ⛔ Public because the same list is the gate's whitelist in
/// `tests/man_page.rs` — a second copy of it there would be a second thing to
/// keep in step with the emitter.
pub const HEADINGS: &[&str] = &[
    ".SH NAME",
    ".SH SYNOPSIS",
    ".SH DESCRIPTION",
    ".SH OPTIONS",
    ".SH SUBCOMMANDS",
];

/// ⛔ The two macros `06-cli.md`:163-164 names, defined by the page that uses them.
///
/// ⛔ `\\fB\\$*\\fR` in Rust source is the bytes `\fB\$*\fR` on the wire: bold,
/// all arguments, roman. ⛔ `\$*` and not `\$1`, because a flag's `.Fl` line
/// carries its spellings and its metavariable as separate arguments.
const DEFINITIONS: &str = ".de It\n.TP\n..\n.de Fl\n\\fB\\$*\\fR\n..\n";

/// ⛔ The page's own prose, and there is deliberately very little of it:
/// `man.md`:159-160 — *"a page generated from the tree cannot go stale — but a
/// prose section hand-written beside it can"*. ⛔ Every sentence below is about
/// the page itself and none of it describes a flag, a host, or a decision that
/// can move.
const DESCRIPTION: &str = ".SH DESCRIPTION\n\
.B podssh\n\
is one command line for reaching a host over a WebSocket relay. Every\n\
subcommand and every flag on this page is rendered from the same table that\n\
renders\n\
.BR \"podssh \\-\\-help\" ,\n\
so this page and the help cannot describe different flags.\n";

/// ⛔ The two options that exist **before** a verb is chosen.
///
/// ⛔ They are not rows of any verb's table, because the top level is not a
/// verb: `--help` and `--version` are read in [`crate::tree::parse`] before a
/// verb is selected. ⛔ The parity gate compares both renderings' copies of
/// them, so a change to `help.rs`'s top-level block fails the gate rather than
/// silently disagreeing with this one.
const TOP_OPTIONS: &[(&str, &str)] =
    &[("-h --help", "Print help"), ("-V --version", "Print version")];

/// ⛔ **The escaping rule, and it is the whole of it.**
///
/// * `\` becomes `\\` — ⛔ otherwise a table string containing `\fB` would
///   change a font, and one containing `\"` would turn its line into a comment.
/// * `-` becomes `\-` — the classic man-page spelling of a literal hyphen.
/// * A `.` or `'` that would **start an output line** is prefixed with `\&`,
///   the zero-width glyph — ⛔ a line beginning with `.` is a *request*, and
///   that is how a help string escapes its own macro (`man.md`:233).
/// * A newline inside the input is honoured **and resets the start-of-line
///   rule**, because a `\n` in a table string must not smuggle a control line
///   in behind the first one. ⛔ This is the half of the rule that a
///   first-character-only check gets wrong.
pub fn text(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let mut at_line_start = true;
    for c in s.chars() {
        match c {
            '\\' => {
                out.push_str("\\\\");
                at_line_start = false;
            }
            '-' => {
                out.push_str("\\-");
                at_line_start = false;
            }
            '\n' => {
                out.push('\n');
                at_line_start = true;
            }
            '.' | '\'' if at_line_start => {
                out.push_str("\\&");
                out.push(c);
                at_line_start = false;
            }
            _ => {
                out.push(c);
                at_line_start = false;
            }
        }
    }
    out
}

/// The `.Fl` line for one row: both spellings a user may type, and the
/// metavariable.
///
/// ⛔ The short spelling is [`FlagRow::spelling`]'s, not a second `format!`,
/// and the long one is [`FlagRow::long`]'s — ⛔ `man.md`:242-243: *"`man.rs`
/// should call them rather than reformat, so help and roff cannot disagree on
/// a spelling."*
pub fn flag_macro(row: &FlagRow) -> String {
    let spelling = row.spelling();
    let long = format!("--{}", row.long);
    let mut line = String::from(".Fl ");
    line.push_str(&text(&spelling));
    if long != spelling {
        line.push(' ');
        line.push_str(&text(&long));
    }
    if let Some(arg) = row.arg {
        line.push(' ');
        line.push_str(&text(arg));
    }
    line
}

/// One flag: the `.It` paragraph, its `.Fl` name line, and its description.
///
/// ⛔ The description is [`crate::help::help_text`]'s — the same function
/// `--help` prints — so that *"accepted and ignored"* and *"refused: use `-W`
/// HOST:PORT"* reach the page without being retyped. ⛔ It is emitted on **one
/// line**: filling is the renderer's job, ⛔ and a wrapped description would
/// stop the parity gate from comparing the sentence byte for byte.
pub fn flag_item(row: &FlagRow) -> String {
    let mut s = String::new();
    let _ = writeln!(s, ".It");
    let _ = writeln!(s, "{}", flag_macro(row));
    let _ = writeln!(s, "{}", text(&crate::help::help_text(row)));
    s
}

/// ⛔ Every flag a verb takes, in the order `--help` prints them: the table's
/// rows, then the universal `--help` that the parser declares for every
/// command.
fn flag_list(verb: &Verb) -> String {
    let mut s = String::new();
    for row in verb.flags {
        s.push_str(&flag_item(row));
    }
    s.push_str(&flag_item(&crate::flags::HELP_FLAG));
    s
}

/// ⛔ `podssh <verb> <tail>`, from [`crate::help::usage_tail`] — the same
/// string `--help` prints under `USAGE:`.
///
/// ⛔ Public because E32's parity gate asserts the page carries this exact
/// string, ⛔ and a second `format!` in the gate would be a second place the
/// synopsis can drift.
pub fn usage_line(verb: &Verb) -> String {
    format!("podssh {} {}", verb.name, crate::help::usage_tail(verb))
}

/// One verb's subsection, as it appears in the full page.
fn verb_block(verb: &Verb) -> String {
    let mut s = String::new();
    let _ = writeln!(s, ".SS {}", text(verb.name));
    let _ = writeln!(s, ".I {}", text(&usage_line(verb)));
    // ⛔ `.br` because fill mode would otherwise run the synopsis straight into
    // the description sentence.
    let _ = writeln!(s, ".br");
    let _ = writeln!(s, "{}", text(verb.about));
    s.push_str(&flag_list(verb));
    s
}

/// One verb's section as a page of its own, for `podssh man <SECTION>`.
///
/// ⛔ `None` for anything that is not a verb, and that `None` is what makes
/// `podssh man nonsense` exit **64** rather than print a page for a section
/// that does not exist (`man.md`:150-153). ⛔ Aliases resolve, so
/// `podssh man irc` renders `chat` — the same resolution `podssh irc --help`
/// gets from [`crate::flags::verb_for`].
pub fn section_page(name: &str) -> Option<String> {
    let verb = crate::flags::verb_for(name)?;
    let mut s = String::new();
    let _ = writeln!(
        s,
        ".TH PODSSH-{} 1 \"podssh {}\"",
        verb.name.to_ascii_uppercase(),
        crate::help::version()
    );
    s.push_str(DEFINITIONS);
    s.push_str(".SH NAME\n");
    let _ = writeln!(s, "podssh {} \\- {}", text(verb.name), text(verb.about));
    s.push_str(".SH SYNOPSIS\n");
    let _ = writeln!(s, ".I {}", text(&usage_line(verb)));
    s.push_str(".SH OPTIONS\n");
    s.push_str(&flag_list(verb));
    Some(s)
}

/// ⛔ **`podssh man --no-pager`, as a `String`.** ⛔ The acceptance reads
/// `head -1 page.1` and expects the `.TH` line, so ⛔ `.TH` is line one and no
/// comment may precede it.
///
/// ⛔ The `.TH` third field carries the **version and not a date**: the version
/// comes from `CARGO_PKG_VERSION`, the same source `podssh --version` reads,
/// so it cannot drift; ⛔ a date would be a second fact about the binary that
/// nothing generates, and ⛔ a page that renders differently on Tuesday is a
/// page the drift gate cannot compare.
pub fn page() -> String {
    let mut s = String::new();
    let _ = writeln!(s, ".TH PODSSH 1 \"podssh {}\"", crate::help::version());
    s.push_str(DEFINITIONS);
    s.push_str(".SH NAME\n");
    let _ = writeln!(s, "podssh \\- {}", text(crate::flags::ABOUT));
    s.push_str(".SH SYNOPSIS\n.B podssh\n.I SUBCOMMAND\n.RI [ options ]\n");
    s.push_str(DESCRIPTION);
    s.push_str(".SH OPTIONS\n");
    for (names, about) in TOP_OPTIONS {
        let _ = writeln!(s, ".It\n.Fl {}\n{}", text(names), text(about));
    }
    s.push_str(".SH SUBCOMMANDS\n");
    for verb in VERBS {
        s.push_str(&verb_block(verb));
    }
    s
}

/// ⛔ **The `man` verb's behaviour.** Returns the process exit code.
///
/// ⛔ The page is the answer, so it goes to **stdout** and it is **the same
/// bytes on every path**: `--no-pager` writes and exits (`06-cli.md`:196), a
/// terminal that cannot be read a key from writes and exits
/// ([`crate::pager::Tty::can_page`]), ⛔ and only a real terminal gets
/// [`crate::pager::page`]. ⛔ The key reader is a parameter so that no test can
/// block on a terminal — the test entry point passes a reader it owns.
pub fn run(
    section: Option<&str>,
    no_pager: bool,
    tty: crate::pager::Tty,
    keys: &mut dyn BufRead,
    out: &mut dyn Write,
    err: &mut dyn Write,
) -> i32 {
    let body = match section {
        None => page(),
        Some(name) => match section_page(name) {
            Some(text) => text,
            None => {
                let _ = writeln!(err, "{}", crate::refuse::unknown_man_section(name));
                return crate::exit_codes::EXIT_USAGE;
            }
        },
    };
    if no_pager || !tty.can_page() {
        // ⛔ A write that failed — a reader that went away, as in
        // `podssh man --no-pager | head -20` — is not a podssh fault and must
        // not turn a readable page into a non-zero exit. E24's table has no
        // code for it, and the acceptance reads `head`'s status there anyway.
        let _ = out.write_all(body.as_bytes());
        let _ = out.flush();
        return 0;
    }
    let _ = crate::pager::page(&body, keys, out, err);
    0
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::flags::FlagKind;
    use std::io::Cursor;

    fn page_lines() -> Vec<String> {
        page().lines().map(|l| l.to_string()).collect()
    }

    /// ⛔ **The acceptance's own reading**: `head -1 page.1` is the `.TH` line,
    /// and `head -20` reaches `.SH NAME` and `.SH DESCRIPTION`.
    #[test]
    fn the_page_is_roff_and_its_first_line_is_th() {
        let lines = page_lines();
        let first = &lines[0];
        assert!(first.starts_with(".TH PODSSH 1 \"podssh "), "{first}");
        assert!(first.contains(&crate::help::version()), "{first}");
        let head: Vec<&str> = lines.iter().take(20).map(String::as_str).collect();
        for want in [".SH NAME", ".SH DESCRIPTION"] {
            assert!(head.contains(&want), "head -20 never reaches {want}: {head:?}");
        }
    }

    /// ⛔ **Plant 7, and the reason the escaper exists.** ⛔ A help string
    /// containing a line that begins with `.` or `\` must not start a macro
    /// and must not change a font, ⛔ and the assertion is **equality with the
    /// intended output** rather than a substring search: a whitelist alone
    /// would accept an injected `.SH`, because `.SH` is a macro this emitter
    /// may legitimately write.
    #[test]
    fn an_injected_line_cannot_start_a_macro() {
        let row = FlagRow {
            short: Some('x'),
            long: "x",
            arg: Some("ARG"),
            kind: FlagKind::Supported,
            help: ".SH INJECTED\n\\fBbold\\fR\n'br nope",
            instead: None,
        };
        let out = flag_item(&row);
        assert_eq!(
            out,
            ".It\n.Fl \\-x \\-\\-x ARG\n\\&.SH INJECTED\n\\\\fBbold\\\\fR\n\\&'br nope\n"
        );
        // ⛔ And stated as the property rather than only as the bytes: the
        // only requests in this item are the two the emitter intended.
        let requests: Vec<&str> = out.lines().filter(|l| l.starts_with('.')).collect();
        assert_eq!(requests, vec![".It", ".Fl \\-x \\-\\-x ARG"], "{out}");
    }

    /// ⛔ **The whitelist, over the real page.** ⛔ Every request line must be
    /// one [`MACROS`] names, and every heading must be one the emitter writes.
    #[test]
    fn the_page_uses_only_the_macros_it_defines() {
        for line in page().lines().chain(section_page("ssh").unwrap().lines()) {
            let Some(first) = line.split_whitespace().next() else { continue };
            if !first.starts_with('.') {
                continue;
            }
            assert!(MACROS.contains(&first), "unintended request {first:?} in {line:?}");
        }
        for line in page().lines() {
            if let Some(h) = HEADINGS.iter().find(|h| line.starts_with(**h)) {
                assert_eq!(line, *h, "a heading with extra text");
            } else if line.starts_with(".SH") {
                panic!("unintended section heading: {line:?}");
            }
        }
    }

    /// ⛔ Every subsection is a verb from the tree, in `--help` order, and the
    /// page names every alias — ⛔ a page that omits a verb is a page that
    /// describes a smaller program than the binary.
    #[test]
    fn every_verb_gets_a_subsection_in_the_trees_order() {
        let page = page();
        let mut at = 0;
        for verb in VERBS {
            let needle = format!(".SS {}\n", verb.name);
            let found = page[at..]
                .find(&needle)
                .unwrap_or_else(|| panic!("the page has no {needle:?} after byte {at}"));
            at += found + needle.len();
        }
        // ⛔ The NAME line is the shared sentence, escaped by the same function
        // the emitter used rather than written out a second time.
        let name_line = format!("podssh \\- {}", text(crate::flags::ABOUT));
        assert!(page.contains(&name_line), "the NAME line {name_line:?} is missing");
    }

    /// ⛔ **Plant 6's unit half: with no terminal there is no pager at all.**
    /// ⛔ The key reader is empty, so a build that entered the pager anyway
    /// would stop at the first screenful — ⛔ which is exactly the defect the
    /// entry's plant names, and this asserts the whole page and nothing on
    /// stderr instead.
    #[test]
    fn with_no_terminal_the_whole_page_is_written_and_nothing_waits() {
        let mut keys = Cursor::new(Vec::new());
        let mut out: Vec<u8> = Vec::new();
        let mut err: Vec<u8> = Vec::new();
        let rc = run(None, false, crate::pager::Tty::none(), &mut keys, &mut out, &mut err);
        assert_eq!(rc, 0);
        assert_eq!(String::from_utf8(out).unwrap(), page());
        assert!(err.is_empty(), "a diagnostic on the no-pager path: {err:?}");
    }

    /// ⛔ `--no-pager` writes and exits **even on a terminal** — `06-cli.md`:196.
    #[test]
    fn no_pager_writes_the_page_even_on_a_terminal() {
        let mut keys = Cursor::new(b"q".to_vec());
        let mut out: Vec<u8> = Vec::new();
        let mut err: Vec<u8> = Vec::new();
        let tty = crate::pager::Tty { stdin: true, stdout: true };
        let rc = run(None, true, tty, &mut keys, &mut out, &mut err);
        assert_eq!(rc, 0);
        assert_eq!(String::from_utf8(out).unwrap(), page());
        assert!(err.is_empty(), "{err:?}");
    }

    /// ⛔ An unknown section is a refusal at exit **64**, naming itself, and
    /// **nothing reaches stdout** (`man.md`:150-153, `06-cli.md`:251-252).
    #[test]
    fn an_unknown_section_refuses_rather_than_printing_a_page() {
        let mut keys = Cursor::new(Vec::new());
        let mut out: Vec<u8> = Vec::new();
        let mut err: Vec<u8> = Vec::new();
        let rc = run(
            Some("nonsense"),
            false,
            crate::pager::Tty::none(),
            &mut keys,
            &mut out,
            &mut err,
        );
        assert_eq!(rc, crate::exit_codes::EXIT_USAGE);
        assert_eq!(rc, 64);
        assert!(out.is_empty(), "an unknown section wrote {} bytes to stdout", out.len());
        let err = String::from_utf8(err).unwrap();
        assert!(err.contains("nonsense"), "{err}");
        assert!(err.contains("ssh"), "the refusal must name the sections: {err}");
    }

    /// ⛔ The control for the test above: a section that **does** exist renders,
    /// and an alias renders its canonical verb.
    #[test]
    fn a_known_section_renders_and_an_alias_resolves() {
        for (given, want) in [("ssh", "ssh"), ("irc", "chat"), ("scp", "cp")] {
            let text = section_page(given).unwrap_or_else(|| panic!("{given} has no section"));
            assert!(text.contains(".SH NAME"), "{given}");
            assert!(text.contains(&format!("podssh {want} ")), "{given}: {text}");
            assert!(text.contains(".Fl \\-\\-help"), "{given}");
        }
    }
}
